language: android
android:
  components:
    - platform-tools
    - tools
    - extra
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-18

script:
  - ./gradlew check assemble :sample:test

